version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d finance" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "7878:7878"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/finance
      - JWT_SECRET=super_secret_key_docker_layer
      - ADMIN_NAME=Admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
